/* Automatically generated by wasm2c */
#ifndef COUNTER_H_GENERATED_
#define COUNTER_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_env;

typedef struct w2c_counter {
  struct w2c_env* w2c_env_instance;
  u32 w2c_g0;
  u32 w2c_0x5F_data_end;
  u32 w2c_0x5F_heap_base;
  wasm_rt_memory_t w2c_memory;
  wasm_rt_funcref_table_t w2c_T0;
} w2c_counter;

void wasm2c_counter_instantiate(w2c_counter*, struct w2c_env*);
void wasm2c_counter_free(w2c_counter*);
wasm_rt_func_type_t wasm2c_counter_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: 'env' 'abort' */
void w2c_env_abort(struct w2c_env*, u32);

/* import: 'env' 'addr_canonicalize' */
u32 w2c_env_addr_canonicalize(struct w2c_env*, u32, u32);

/* import: 'env' 'addr_humanize' */
u32 w2c_env_addr_humanize(struct w2c_env*, u32, u32);

/* import: 'env' 'addr_validate' */
u32 w2c_env_addr_validate(struct w2c_env*, u32);

/* import: 'env' 'db_next' */
u32 w2c_env_db_next(struct w2c_env*, u32);

/* import: 'env' 'db_read' */
u32 w2c_env_db_read(struct w2c_env*, u32);

/* import: 'env' 'db_remove' */
void w2c_env_db_remove(struct w2c_env*, u32);

/* import: 'env' 'db_scan' */
u32 w2c_env_db_scan(struct w2c_env*, u32, u32, u32);

/* import: 'env' 'db_write' */
void w2c_env_db_write(struct w2c_env*, u32, u32);

/* import: 'env' 'debug' */
void w2c_env_debug(struct w2c_env*, u32);

/* import: 'env' 'ed25519_batch_verify' */
u32 w2c_env_ed25519_batch_verify(struct w2c_env*, u32, u32, u32);

/* import: 'env' 'ed25519_verify' */
u32 w2c_env_ed25519_verify(struct w2c_env*, u32, u32, u32);

/* import: 'env' 'query_chain' */
u32 w2c_env_query_chain(struct w2c_env*, u32);

/* import: 'env' 'secp256k1_recover_pubkey' */
u64 w2c_env_secp256k1_recover_pubkey(struct w2c_env*, u32, u32, u32);

/* import: 'env' 'secp256k1_verify' */
u32 w2c_env_secp256k1_verify(struct w2c_env*, u32, u32, u32);

/* export: 'memory' */
wasm_rt_memory_t* w2c_counter_memory(w2c_counter* instance);

/* export: 'instantiate' */
u32 w2c_counter_instantiate(w2c_counter*, u32, u32, u32);

/* export: 'execute' */
u32 w2c_counter_execute(w2c_counter*, u32, u32, u32);

/* export: 'sudo' */
u32 w2c_counter_sudo(w2c_counter*, u32, u32);

/* export: 'query' */
u32 w2c_counter_query(w2c_counter*, u32, u32);

/* export: 'allocate' */
u32 w2c_counter_allocate(w2c_counter*, u32);

/* export: 'deallocate' */
void w2c_counter_deallocate(w2c_counter*, u32);

/* export: 'requires_staking' */
void w2c_counter_requires_staking(w2c_counter*);

/* export: 'requires_iterator' */
void w2c_counter_requires_iterator(w2c_counter*);

/* export: 'interface_version_8' */
void w2c_counter_interface_version_8(w2c_counter*);

/* export: '__data_end' */
u32* w2c_counter_0x5F_data_end(w2c_counter* instance);

/* export: '__heap_base' */
u32* w2c_counter_0x5F_heap_base(w2c_counter* instance);

#ifdef __cplusplus
}
#endif

#endif  /* COUNTER_H_GENERATED_ */
