type = "cosmos"
name = "banksy"
rpc_url = "http://127.0.0.1:1317"
grpc_url = "http://0.0.0.0:26656"
websocket_url = "ws://127.0.0.1:9988/websocket"
chain_id = "test-1"
client_id = "07-tendermint-0"
connection_id = "connection-0"
account_prefix = "centauri"
fee_denom = "ppica"
fee_amount = "4000"
gas_limit = 9223372036854775806
store_prefix = "ibc"
max_tx_size = 200000
wasm_code_id = "58c7623a3ab78f4cb2e4c5d02876ac36c3b38bb472118173a7ec7faa688a66d2"
channel_whitelist = [["channel-2", "transfer"]]
mnemonic = "decorate bright ozone fork gallery riot bus exhaust worth way bone indoor calm squirrel merry zero scheme cotton until shop any excess stage laundry"
skip_optional_client_updates = true
max_packets_to_process = 200
