type = "cosmos"
name = "centauri"
rpc_url = "http://127.0.0.1:26657/"
grpc_url = "http://127.0.0.1:9090/"
websocket_url = "ws://127.0.0.1:26657/websocket"
chain_id = "centauri-dev"
client_id = "07-tendermint-0"
connection_id = "connection-0"
account_prefix = "centauri"
fee_denom = "upica"
fee_amount = "10000000000000000"
gas_limit = 9223372036854775806
store_prefix = "ibc"
max_tx_size = 20000000
wasm_code_id = "58c7623a3ab78f4cb2e4c5d02876ac36c3b38bb472118173a7ec7faa688a66d2"
channel_whitelist = [["channel-0", "transfer"]]
mnemonic = "decorate bright ozone fork gallery riot bus exhaust worth way bone indoor calm squirrel merry zero scheme cotton until shop any excess stage laundry"
skip_optional_client_updates = false
max_packets_to_process = 50
skip_tokens_list = []