type = "cosmos"
name = "centauri"
rpc_url = "http://127.0.0.1:26657/"
grpc_url = "http://127.0.0.1:9090/"
websocket_url = "ws://127.0.0.1:26657/websocket"
chain_id = "test-1"
client_id = "07-tendermint-0"
connection_id = "connection-0"
account_prefix = "centauri"
fee_denom = "ppica"
fee_amount = "400"
gas_limit = 9223372036854775806
store_prefix = "ibc"
max_tx_size = 20000000
wasm_code_id = "7c6f5ceffb328a7660e21b73564595650d19a7eaf2678bd32e199bc1ab5009a0"
channel_whitelist = [["channel-0", "transfer"]]
mnemonic = "bottom loan skill merry east cradle onion journey palm apology verb edit desert impose absurd oil bubble sweet glove shallow size build burst effort"
skip_optional_client_updates = false
max_packets_to_process = 50
skip_tokens_list = []