type = "picasso_rococo"
name = "rococo-local-alice"
para_id = 2087
parachain_rpc_url = "ws://127.0.0.1:9988"
relay_chain_rpc_url = "ws://127.0.0.1:9944"
client_id = "08-wasm-0"
connection_id = "connection-1"
channel_whitelist = []
commitment_prefix = "0x6962632f"
private_key = "//Alice"
ss58_version = 49
key_type = "sr25519"
finality_protocol = "Grandpa"