---
    name: Release Binary
    
    on:
      release:
        types: [created]
    
    permissions:
      contents: read
      packages: write
      
    jobs:
      release:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - 
            name: Set up QEMU
            uses: docker/setup-qemu-action@v2
          - 
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
            
          - name: Docker compose
            run: docker-compose up -d
    
          - name: Copy binary
            run: docker cp composable-centauri_node_1:/bin/picad ./picad
    
          - name: Save sha256 sum
            run: sha256sum ./picad > ./centaurid_sha256.txt
    
          - name: Release
            uses: softprops/action-gh-release@v1        
            with:
              token: ${{ github.token }}
              files: |
                centaurid
                centaurid_sha256.txt
    
          - name: Dump docker logs on failure
            if: failure()
            uses: jwalton/gh-docker-logs@v2